apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pv-claim-primary
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi