apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-sec1-deployment
  labels:
    app: secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-sec1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-sec1
        type: secondary
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: type
      #           operator: In
      #           values:
      #           - worker 
      #         - key: zone
      #           operator: In
      #           values:
      #           - us-west 
      hostname: mssql-sec1  
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: task-pv-storage-secondary1
          persistentVolumeClaim:
            claimName: mssql-pv-claim-secondary1
      containers:
      - name:  mssql-sec1
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name:  MSSQL_PID
          value:  "Developer"
        - name:  ACCEPT_EULA
          value: "Y"
        - name:  MSSQL_ENABLE_HADR
          value: "1"
        - name:  MSSQL_AGENT_ENABLED
          value: "true"
        - name:  MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  mssql
              key: SA_PASSWORD
        resources:
          limits:
            memory: 3G
        volumeMounts:
          - name:  task-pv-storage-secondary1
            mountPath:  /var/opt/mssql
    hostname: mssql-sec1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-sec2-deployment
  labels:
    app: secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql-sec2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql-sec2
        type: secondary
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: type
      #           operator: In
      #           values:
      #           - worker 
      #         - key: zone
      #           operator: In
      #           values:
      #           - useast
      hostname: mssql-sec2  
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
        - name: task-pv-storage-secondary2
          persistentVolumeClaim:
            claimName: mssql-pv-claim-secondary2
      containers:
      - name:  mssql-sec2
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name:  MSSQL_PID
          value:  "Developer"
        - name:  ACCEPT_EULA
          value: "Y"
        - name:  MSSQL_ENABLE_HADR
          value: "1"
        - name:  MSSQL_AGENT_ENABLED
          value: "true"
        - name:  MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  mssql
              key: SA_PASSWORD
        resources:
          limits:
            memory: 3G
        volumeMounts:
          - name:  task-pv-storage-secondary2
            mountPath:  /var/opt/mssql
    hostname: mssql-sec2
